server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mooc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 20031115
  freemarker:
    charset: UTF-8
    content-type: text/html; charset=UTF-8
    expose-spring-macro-helpers: true
    expose-session-attributes: true
    expose-request-attributes: true
    suffix: .ftl
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      default_encoding: UTF-8
      auto_import: common/common.ftl as common
  data:
    mongodb:
      uri: mongodb://localhost/cspiration
  redis:
    host: localhost
    port: 6379
    database: 0
  application:
    name: cson-mooc-web
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      use-generated-keys: true
      default-executor-type: reuse
      default-statement-timeout: 600
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cspiration.mooc.entity

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
logging:
  file:
    name: cspiration.log


